sudo: required

language: python
python:
  - "3.6"

services:
- docker

env:
  global:
    - DJANGO=2.1
    - SECRET_KEY=65h_n86*1!=ae_pxqaxcgkc3pc(fd+hi0sih+-^%3$u_yprihc

install:
  - docker-compose build
  - pip install pycodestyle
  - pip install coverage
  - pip install -r requirements.txt
    
before_script: 
  - mysql -e 'create database mytestdatabase;' -u root
  - mysql -e 'create database eventmanager;' -u root
      
script:
  - cd eventmanager
  - pycodestyle .
  - docker run event-manager /bin/sh --settings=eventmanager.travis.settings -c "eventmanager/manage.py test eventmanager/"
