sudo: required

language: python
python:
  - "3.6"

services:
- docker

env:
  global:
    - DJANGO=2.1
    - SECRET_KEY=65h_n86*1!=ae_pxqaxcgkc3pc(fd+hi0sih+-^%3$u_yprihc
    - DJANGO_SETTINGS_MODULE=eventmanager.settings

install:
  - docker-compose build
  - pip install django
  - pip install pycodestyle
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - cd eventmanager
  - pycodestyle .
  - docker run event-manager /bin/sh -c "eventmanager/manage.py test eventmanager/"
  - pwd && cd eventmanager && pytest --cov=eventmanager/


after_success:
  - coveralls
