sudo: required

language: python

services:
- docker

env:
  -DJANGO=2.1
  global:
    - SECRET_KEY=65h_n86*1!=ae_pxqaxcgkc3pc(fd+hi0sih+-^%3$u_yprihc
      
install:
  - docker-compose build
  - pip install pycodestyle

script:
  - cd eventmanager
  - pycodestyle . --exclude settings.py
  - docker-compose up
  - docker exec -it event-manager.container /bin/bash
  - python eventmanager/manage.py test
 

  

