language: python

install:
  - pip install pycodestyle
  - pip3 install wheel -r requirements.txt

script:
  - cd eventmanager
  - pycodestyle . --exclude settings.py
  -  python /code/eventmanager/manage.py test
