sudo: required

language: python
python:
  - "3.7"

services:
- docker
- mysql

env:
  global:
    - DJANGO=2.1
    - SECRET_KEY=65h_n86*1!=ae_pxqaxcgkc3pc(fd+hi0sih+-^%3$u_yprihc

install:
  - docker-compose build
  - pip install pycodestyle
  - pip install coverage
  - pip install -r requirements.txt

script:
  - cd eventmanager
  - pycodestyle .
  - docker run event-manager  /bin/sh -c "eventmanager/manage.py  test eventmanager/ --settings=eventmanager.travis"
