sudo: required

language: python

services:
- docker

env:
  -DJANGO=2.1 DB=mysql
  global:
    - USER_ID=1000
    - USER_NAME=karina
    - GROUP_ID=1000
    - GROUP_NAME=karina
    - SECRET_KEY=65h_n86*1!=ae_pxqaxcgkc3pc(fd+hi0sih+-^%3$u_yprihc
    - MYSQL_DATABASE=eventmanager
    - MYSQL_USER=eventmanager
    - MYSQL_PASSWORD=eventmanager
    - MYSQL_ROOT_PASSWORD=eventmanager
      
install:
  - docker-compose pull
  - docker-compose build
  - pip install pycodestyle python

before_script:
  - mysql -e 'create database test;' -u root

script:
  - cd eventmanager
  - pycodestyle . --exclude settings.py
  - docker-compose up
  - docker exec -it event-manager.container /bin/bash
  - python eventmanager/manage.py test
 

  

