sudo: required

language: python
python:
  - "3.7"

services:
- docker

env:
  global:
    - DJANGO=2.1
    - SECRET_KEY=65h_n86*1!=ae_pxqaxcgkc3pc(fd+hi0sih+-^%3$u_yprihc
    
install:
  - docker-compose build
  - pip install pycodestyle

script:
  - cd eventmanager
  - pycodestyle .
  - docker run event-manager.container /bin/sh  eventmanager/manage.py test