# Generated by Django 2.1.2 on 2018-11-20 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='250 character limit', max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(help_text='Plain text, any formatting or links will be removed', verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Event starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Event ends at')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(help_text='Can select many Categories', related_name='categories', to='categories.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['title'],
            },
        ),
    ]
