# Generated by Django 2.1.2 on 2018-11-02 16:50
from django.db import migrations, models
import events.models
class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('categories', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='250 character limit', max_length=250, verbose_name='Title')),
                ('description', models.TextField(help_text='Plain text, any formatting or links will be removed', verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=events.models.get_image_path)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Event starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Event ends at')),
                ('category', models.ManyToManyField(help_text='Can select many Categories', related_name='categories', to='categories.Category', verbose_name='Categories')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]