# Generated by Django 2.1.2 on 2018-11-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Plain text, any formatting or links will be removed', max_length=250, verbose_name='Author')),
                ('title', models.CharField(help_text='250 character limit', max_length=500, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('remote_address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Remote Address')),
                ('remote_city', models.CharField(blank=True, max_length=512, null=True, verbose_name='Remote City')),
                ('remote_country', models.CharField(blank=True, max_length=512, null=True, verbose_name='Remote Country')),
                ('remote_agent', models.CharField(blank=True, max_length=512, null=True, verbose_name='Remote Agent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.Event')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
