# Generated by Django 2.1.5 on 2019-02-23 21:22

from django.db import migrations, models
import django_countries.fields
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='400 character limit', max_length=400, null=True, verbose_name='Event Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, validators=[events.models.future], verbose_name='Event ends at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, validators=[events.models.future], verbose_name='Event starts at'),
        ),
    ]
