# Generated by Django 2.1.7 on 2019-04-17 18:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=tinymce.models.HTMLField(max_length=500, verbose_name='Content'),
        ),
    ]
