# Generated by Django 2.1.5 on 2019-01-27 10:40

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, validators=[events.models.future], verbose_name='Event ends at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, validators=[events.models.future], verbose_name='Event starts at'),
        ),
    ]
