# Generated by Django 2.1.5 on 2019-02-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190127_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='400 character limit', max_length=400, null=True, verbose_name='Event Location'),
        ),
    ]
