# Generated by Django 2.1.7 on 2019-04-17 18:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190417_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(help_text='Plain text, any formatting or links will be removed', verbose_name='Description'),
        ),
    ]
