# Generated by Django 2.1.2 on 2018-11-23 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20181121_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='remote_address',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='remote_agent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='remote_city',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='remote_country',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, related_name='attendees', to=settings.AUTH_USER_MODEL, verbose_name='Attendees'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated at'),
        ),
    ]
