# Generated by Django 2.1.2 on 2018-11-02 17:58
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('events', '0004_auto_20181102_1750'),
    ]
    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='eventmanager/media/events_covers/'),
        ),
    ]