# Generated by Django 2.1.2 on 2018-12-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20181130_1340'),
        ('events', '0005_auto_20181130_1438'),
    ]

    operations = [
    ]
