# Generated by Django 2.1.2 on 2018-11-14 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20181108_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hosted_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Host'),
        ),
    ]
