# Generated by Django 2.1.2 on 2018-11-09 11:07

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20181108_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True, verbose_name='Event ends at'),
        ),
    ]
