# Generated by Django 2.1.2 on 2018-11-14 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_event_hosted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hosted_by',
        ),
        migrations.AddField(
            model_name='event',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
