# Generated by Django 2.1.2 on 2018-12-03 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_auto_20181203_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team', to=settings.AUTH_USER_MODEL, verbose_name='Team'),
        ),
    ]
