# Generated by Django 2.1.2 on 2018-12-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.TextField(default='1', verbose_name='visibility'),
        ),
    ]
