# Generated by Django 2.1.2 on 2018-12-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20181205_2117'),
        ('events', '0010_event_team_members'),
    ]

    operations = [
    ]
