# Generated by Django 2.1.2 on 2018-11-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdetails',
            options={'verbose_name': 'Account Details', 'verbose_name_plural': 'Account Details'},
        ),
    ]
