# Generated by Django 2.1.5 on 2019-01-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
