# Generated by Django 2.1.5 on 2019-01-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_friendrequest_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='slug',
        ),
    ]
