# Generated by Django 2.1.2 on 2018-12-02 09:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_auto_20181202_0902'),
        ('accounts', '0003_auto_20181202_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inivite',
            new_name='Invite',
        ),
    ]
