# Generated by Django 2.1.2 on 2018-12-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181202_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='event',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='invited_user',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
