# Generated by Django 2.1.2 on 2018-11-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
    ]
