# Generated by Django 2.1.2 on 2018-11-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(
                blank=True,
                help_text='Plain text,\
                            any formatting or links will be removed',
                null=True,
                verbose_name='Description'
            ),
        ),
    ]
