# Generated by Django 2.1.5 on 2019-03-20 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0002_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('description', models.TextField(blank=True, help_text='Plain text, any formatting or links will be removed', null=True, verbose_name='Description')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='SuggestedCategories')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggested Category',
                'verbose_name_plural': 'Suggested Categories',
                'ordering': ['name'],
            },
        ),
    ]
