# Generated by Django 2.1.5 on 2019-03-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_suggestedcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedcategory',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name'),
        ),
    ]
