# Generated by Django 2.1.2 on 2019-01-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Plain text, any formatting or links will be removed', null=True, verbose_name='Description'),
        ),
    ]
